#!/bin/bash

# ABSTRACT: Shows all packages depending on a specific atom

source "${LIBDIR}/core-functions.sh" || exit 1

[[ $# == 1 ]]  || die "Expected argument [atom] in: ${cmdname} [atom]"
set -euo pipefail

atom=$1;

shift
require_bin qdepends app-portage/portage-utils
require_bin sort sys-apps/coreutils
(
  einfo "revdep scanning for ${atom}"
  qdepends --nocolor --quiet --quiet --depend --rdepend --pdepend --bdepend --format "%{CAT}/%{PN}:%{SLOT}" --query "${atom}" ||
    ewarn "No matches"
) | sort -u
# help: Invocation:
# help:   gentoo-perl installed-deps-atom [spec]
# help:
# help: Example:
# help:   gentoo-perl installed-deps-atom "dev-lang/perl:0/5.22="
# help:
# help: Outputs:
# help:   A list of all packages in Category/Package-Name:SLOT format
# help:   which have a dependency matching those specified.
