#!/bin/bash

# ABSTRACT: Shows all packages that currently depend on a given perl subslot

source "${LIBDIR}/core-functions.sh" || exit 1

[[ $# == 1 ]]  || die "${FULL_COMMAND:-$0}: Expected argument [perl-version] in: ${FULL_COMMAND:-$0} [perl-version]"
set -euo pipefail

subslot=$1;

shift
require_bin xargs sys-apps/findutils
require_bin qatom app-portage/portage-utils
require_bin qdepends app-portage/portage-utils
require_bin sed sys-apps/sed
require_bin sort sys-apps/coreutils

(
    einfo "revdep DEPEND scanning"
    qdepends --nocolor --depend --quiet --query "dev-lang/perl:0/${subslot}=" |\
           xargs qdepends --nocolor --quiet -k SLOT | sed 's/: /:/'           |\
           xargs qatom --quiet --nocolor --format "%{CATEGORY}/%{PN}%[SLOT]"  |\
           sed -r 's|:([^/]*)/[^/]*|:\1|'       || ewarn "No matches in DEPEND"


    einfo "revdep RDEPEND scanning"
    qdepends --nocolor --rdepend --quiet --query "dev-lang/perl:0/${subslot}=" |\
           xargs qdepends --nocolor --quiet -k SLOT | sed 's/: /:/'            |\
           xargs qatom --quiet --nocolor --format "%{CATEGORY}/%{PN}%[SLOT]"   |\
           sed -r 's|:([^/]*)/[^/]*|:\1|'       || ewarn "No matches in RDEPEND"

    einfo "revdep PDEPEND scanning"
    qdepends --nocolor --pdepend --quiet --query "dev-lang/perl:0/${subslot}=" |\
           xargs qdepends --nocolor --quiet -k SLOT | sed 's/: /:/'           |\
           xargs qatom --quiet --nocolor --format "%{CATEGORY}/%{PN}%[SLOT]"   |\
           sed -r 's|:([^/]*)/[^/]*|:\1|' || ewarn "No matches in PDEPEND"

) | sort -u

# help: Invocation:
# help:   gentoo-perl installed-deps-perl-subslot [perl-subslot-version]
# help:
# help: Example:
# help:   gentoo-perl installed-deps-perl-subslot 5.22
# help:
# help: Outputs:
# help:   A list of all packages in Category/Package-Name format
# help:   which in some way depend on dev-lang/perl:0/5.22=
# help:
# help: Note that [perl-subslot-version] is not typically 5.22.3 or similar,
# help: but 5.22 , the ABI version.

