#!/bin/bash

# ABSTRACT: Lists all installed virtuals

source "${LIBDIR}/core-functions.sh" || exit 1

set -euo pipefail

require_bin xargs sys-apps/findutils
require_bin qatom app-portage/portage-utils
require_bin qdepends app-portage/portage-utils
require_bin sed sys-apps/sed

portageq match "${EPREFIX:-/}" "virtual/perl-*"                     |\
  xargs qdepends --nocolor --quiet -k SLOT | sed 's/: /:/'          |\
  xargs qatom --quiet --nocolor --format "%{CATEGORY}/%{PN}%[SLOT]" |\
  sed -r 's|:([^/]*)/[^/]*|:\1|'

# help: Invocation:
# help:   gentoo-perl installed-perl-virtuals
# help:
# help: Outputs:
# help:   A list of all installed perl-* packages in virtual/
# help:
# help: These items can be removed in urgent situations to trick portage's hand
# help: as removel of these items typically have no direct effect.
# help:
# help: But otherwise, these packages need installed/rebuilt on upgrades.
