#!/bin/bash

# ABSTRACT: Shows all installed packages that depend on Perl

source "${LIBDIR}/core-functions.sh" || exit 1

set -euo pipefail

require_bin xargs sys-apps/findutils
require_bin qatom app-portage/portage-utils
require_bin qdepends app-portage/portage-utils
require_bin sed sys-apps/sed
require_bin sort sys-apps/coreutils

(
    einfo "revdep DEPEND scanning"
    qdepends --nocolor --depend --quiet --query dev-lang/perl                 |\
           xargs qdepends --nocolor --quiet -k SLOT | sed 's/: /:/'           |\
           xargs qatom --quiet --nocolor --format "%{CATEGORY}/%{PN}%[SLOT]"  |\
           sed -r 's|:([^/])*/[^/]*|:\1|'

    einfo "revdep RDEPEND scanning"
    qdepends --nocolor --rdepend --quiet --query dev-lang/perl                |\
           xargs qdepends --nocolor --quiet -k SLOT | sed 's/: /:/'           |\
           xargs qatom --quiet --nocolor --format "%{CATEGORY}/%{PN}%[SLOT]"  |\
           sed -r 's|:([^/])*/[^/]*|:\1|'


    einfo "revdep PDEPEND scanning"
    qdepends --nocolor --pdepend --quiet --query dev-lang/perl                |\
           xargs qdepends --nocolor --quiet -k SLOT | sed 's/: /:/'           |\
           xargs qatom --quiet --nocolor --format "%{CATEGORY}/%{PN}%[SLOT]"  |\
           sed -r 's|:([^/])*/[^/]*|:\1|'

) | sort -u

# help: Invocation:
# help:   gentoo-perl installed-deps-perl
# help:
# help: Outputs:
# help:   A list of all packages in Category/Package-Name format
# help:   which in some way depend on dev-lang/perl
