#!/bin/bash

# ABSTRACT: Lists all installed virtuals

source "${LIBDIR}/core-functions.sh" || exit 1

set -euo pipefail

dorun installed-match-atom "virtual/perl-*"

# help: Invocation:
# help:   gentoo-perl installed-perl-virtuals
# help:
# help: Outputs:
# help:   A list of all installed perl-* packages in virtual/
# help:
# help: These items can be removed in urgent situations to trick portage's hand
# help: as removel of these items typically have no direct effect.
# help:
# help: But otherwise, these packages need installed/rebuilt on upgrades.
