#!/bin/bash

# ABSTRACT: Lists all packages installed in perl-core

source "${LIBDIR}/core-functions.sh" || exit 1

set -euo pipefail

dorun installed-match-atom "perl-core/*"

# help: Invocation:
# help:   gentoo-perl installed-perl-core
# help:
# help: Outputs:
# help:   A list of all installed packages in perl-core/
# help:
# help: These items can typically be removed, as Perl's strategy
# help: will basically resurrect them when they're missing,
# help: and they will mostly continue working, but in a degraded
# help: state due to them all being fallthrough provided by
# help: dev-lang/perl

