#!/bin/bash
( [[ $# -gt 0 ]] && [[ $# -lt 2 ]] ) || _gentoo_perl_die "${0}: Expected ${0} [previous-perl-version]"
local subslot=$1;
shift
set -euo pipefail
        
(
  _gentoo_perl_info "Scanning virtual/perl-*"
  installed-perl-virtual
  _gentoo_perl_info "Scanning Subslot-Redeps of dev-lang/perl:0/${subslot}"
  installed-deps-perl-subslot "${subslot}"
) | sort -u

