#!/bin/bash

# ABSTRACT: Produces a list of all packages that should be rebuilt when upgrading perl
source "${LIBDIR}/core-functions.sh" || exit 1
require_bin sort sys-apps/coreutils

[[ $# -gt  0 ]] || die "Expected [previous-perl-version] in ${cmdname} [previous-perl-version] [wanted-perl-version]"
[[ $# -gt  1 ]] || die "Expected [wanted-perl-version] in ${cmdname} [previous-perl-version] [wanted-perl-version]"
[[ $# -lt  3 ]] || die "Too many arguments, expected 2 at most."

subslot=$1;
shift
target=$1
shift

set -euo pipefail

(
  #einfo "Scanning virtual/perl-*"
  #dorun installed-perl-virtuals || ewarn "No Perl Virtuals detected"
  einfo "Scanning Subslot-Redeps for upgrade to dev-lang/perl:0/${target}"
  dorun installed-deps-perl-subslot-rebuild "${target}"  || ewarn "No subslot deps on Perls other than 0/${target} detected"
) | sort -u

# help: Invocation:
# help:   gentoo-perl print-perl-upgrade-set [oldABI] [newABI]
# help:
# help: Example:
# help:   gentoo-perl installed-deps-perl-subslot 5.22 5.24 | tee /etc/portage/sets/perl-upgrade
# help:
# help: Outputs:
# help:   A list of all packages (with slots) that should be rebuilt in order
# help:   for dev-lang/perl to be upgraded from "oldABI" to "newABI"
