#!/bin/bash

# ABSTRACT: Checks for the presense of all required tools

source "${LIBDIR}/core-functions.sh"

set -euo pipefail

einfo "Testing ...."
require_bin portageq sys-apps/portage
require_bin qatom app-portage/portage-utils
require_bin qdepends app-portage/portage-utils
require_bin xargs sys-apps/findutils
require_bin sed sys-apps/sed
require_bin sort sys-apps/coreutils
require_bin grep sys-apps/grep
require_bin wc sys-apps/coreutils
einfo "OK"
