#!/bin/bash

# ABSTRACT: Print the version of gentoo-perl helpers

echo 0.3.0

# help: Invocation
# help:   gentoo-perl version
# help:
# help: Outputs:
# help:   The version of the gentoo-perl helper suite
